jmouse.web.app=pet-gallery
jmouse.web.server.configuration.tomcat.port=8091
jmouse.web.server.configuration.tomcat.temporary=pet-gallery-tomcat
jmouse.web.enable=true
jmouse.mvc.internal-controller.enabled=true