package org.jmouse.query.sql.mapping;

import org.jmouse.jdbc.dialect.Dialect;
import org.jmouse.query.sql.Fragment;

import java.util.ArrayList;
import java.util.List;

/**
 * A join, assembled rather than concatenated.
 *
 * <p>⚠️ <strong>It exists so that nobody writes {@code "LEFT JOIN " + table + " " + alias + " ON " + …}
 * again.</strong> That line is unreadable, unquoted, and impossible to check by eye — and it was living
 * in a <em>product's</em> code, the least reviewed place in the whole path. Here the shape is written
 * once, the identifiers go through the dialect, and a condition that binds a value carries the value
 * with it.</p>
 *
 * <pre>{@code
 * Join.left(table, alias)
 *     .on(alias, foreignKey).equalTo(target.qualifiedKey())
 *     .and(alias, keyColumn).equalToValue(attribute.source())
 *     .toFragment(dialect);
 * }</pre>
 *
 * @author Ivan Hontarenko (Mr. Jerry Mouse)
 * @author ihontarenko@gmail.com
 */
public final class Join {

    private final String          kind;
    private final String          table;
    private final String          alias;
    private final List<Condition> conditions = new ArrayList<>();

    private Join(String kind, String table, String alias) {
        this.kind = kind;
        this.table = table;
        this.alias = alias;
    }

    /**
     * A {@code LEFT JOIN}.
     *
     * <p>⚠️ Left rather than inner, and it is a semantic choice rather than a default. A row that has no
     * such attribute must survive the join and arrive as {@code NULL}, because SQL's three-valued logic
     * is what the language promises for a missing value — an inner join would silently drop those rows
     * before any condition saw them, turning *"has no such field"* into *"does not exist"*.</p>
     *
     * @param table the table to join
     * @param alias what to call it here
     * @return a join to add conditions to
     */
    public static Join left(String table, String alias) {
        return new Join("LEFT JOIN", table, alias);
    }

    /** An {@code INNER JOIN}, for a relation that is genuinely required. */
    public static Join inner(String table, String alias) {
        return new Join("INNER JOIN", table, alias);
    }

    /** Begins the first condition, on a column of this join's table. */
    public ConditionBuilder on(String owner, String column) {
        return new ConditionBuilder(this, owner, column);
    }

    /** Begins a further condition. Reads better than repeating {@code on}. */
    public ConditionBuilder and(String owner, String column) {
        return new ConditionBuilder(this, owner, column);
    }

    /**
     * Renders the join, quoting identifiers this dialect's way.
     *
     * <p>⚠️ <strong>Rendering is deferred to here on purpose.</strong> A condition built as text at the
     * call site could not be quoted — the builder has no dialect — and the result was a join whose table
     * was quoted while its {@code ON} columns were not. That works until a column is called
     * {@code order}, and then fails somewhere nobody is looking.</p>
     *
     * <p>Aliases are never quoted: they are generated by the context, so they are always safe, and
     * quoting them would only make the SQL harder to read.</p>
     *
     * @param dialect the database this is for
     * @return the join and the values its conditions bind
     */
    public Fragment toFragment(Dialect dialect) {
        StringBuilder written = new StringBuilder(kind)
                .append(' ').append(dialect.quote(table))
                .append(' ').append(alias);

        List<Object> values = new ArrayList<>();

        for (int index = 0; index < conditions.size(); index++) {
            Condition condition = conditions.get(index);

            written.append(index == 0 ? " ON " : " AND ").append(condition.render(dialect));
            values.addAll(condition.values());
        }

        return new Fragment(written.toString(), values);
    }

    /** One comparison inside a join's {@code ON}, kept unrendered until a dialect is known. */
    private record Condition(String owner, String column, String qualified, Object value, boolean bound) {

        String render(Dialect dialect) {
            String left = "%s.%s".formatted(owner, dialect.quote(column));

            return bound ? "%s = ?".formatted(left) : "%s = %s".formatted(left, qualified);
        }

        List<Object> values() {
            return bound ? List.of(value) : List.of();
        }
    }

    /** Builds one condition and hands the join back. */
    public static final class ConditionBuilder {

        private final Join   join;
        private final String owner;
        private final String column;

        private ConditionBuilder(Join join, String owner, String column) {
            this.join = join;
            this.owner = owner;
            this.column = column;
        }

        /**
         * Compares against another qualified column — {@code j1.`entry_id` = e.`id`}.
         *
         * @param qualifiedColumn the other side, already qualified and quoted by the context
         * @return the join, for the next condition
         */
        public Join equalTo(String qualifiedColumn) {
            join.conditions.add(new Condition(owner, column, qualifiedColumn, null, false));

            return join;
        }

        /**
         * Compares against a value.
         *
         * <p>⚠️ <strong>Bound, never written in.</strong> An attribute's name comes from a schema today
         * and could come from anywhere tomorrow; a join that wrote it into the SQL text would be a join
         * with an injection in it, in the code least likely to be read.</p>
         *
         * @param value the value to compare against
         * @return the join, for the next condition
         */
        public Join equalToValue(Object value) {
            join.conditions.add(new Condition(owner, column, null, value, true));

            return join;
        }
    }
}
