package org.jmouse.beans.events;

public enum BeanContextEventName {
    CONTEXT_REFRESH_START,
    CONTEXT_REFRESH_FINISH,

    DEFINITION_REGISTERED,
    DEFINITION_DUPLICATE,

    BEAN_LOOKUP_START,
    BEAN_FOUND,
    BEAN_NOT_FOUND,

    BEAN_CREATE_START,
    BEAN_CREATED,
    BEAN_CREATE_FAILED,

    BEAN_INIT_START,
    BEAN_PROCESSED_BEFORE_INIT,
    BEAN_INITIALIZER_INVOKED,
    BEAN_PROCESSED_AFTER_INIT,
    BEAN_INIT_FINISH,

    CONTEXT_ERROR,
    GENERAL_ERROR
}
